use_deepspeed: true
deepspeed_config: conf/deepspeed_zero2.json

corelm: ar_delay
corelm_conf:
    share_emb: false
    att_unit: 2048
    hf_model_tag: EleutherAI/pythia-1b

# Dataloader
batch_type: numel
batch_bins: 30000
num_iters_per_epoch: 10000
max_epoch: 60
num_workers: 8
drop_last_iter: true
log_interval: 1000
encoder_decoder_format: false
codec_token_per_frame: 8 # encodec
codec_token_in_use: 8
speaker_prompt_length: 500 # 50fps, a.k.a., 10s
seed: 2
