frontend: codec     # embedding + positional encoding
frontend_conf:
    token_bias: 2
    patch_size: 8
    positional_dropout_rate: 0.1
    hf_model_tag: espnet/mls-multi_soundstream_16k



# specaug: specaug
# specaug_conf:
#     apply_time_warp: true
#     time_warp_window: 5
#     time_warp_mode: bicubic
#     apply_freq_mask: true
#     freq_mask_width_range:
#     - 0
#     - 30
#     num_freq_mask: 2
#     apply_time_mask: true
#     time_mask_width_range:
#     - 0
#     - 40
#     num_time_mask: 2

encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 8
    linear_units: 256
    num_blocks: 4
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 256
    num_blocks: 4
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

model: discrete_asr
model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.1
    patch_size: 8
    length_normalized_loss: false
    share_decoder_input_output_embed: false
    share_encoder_decoder_input_embed: false
    extract_feats_in_collect_stats: false

use_amp: false
unused_parameters: true
log_interval: 500
batch_type: numel
batch_bins: 120000000
num_iters_per_epoch: 2000
accum_grad: 1
max_epoch: 400
num_att_plot: 0
patience: 10
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
early_stopping_criterion:
    - valid
    - acc
    - max
keep_nbest_models: 5

optim: adam
optim_conf:
    lr: 0.00001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000