
codec_conf:
    token_bias: 2
    patch_size: 8
    positional_dropout_rate: 0.1
    hf_model_tag: espnet/mls-audioset_soundstream_16k

encoder_conf:
  d_model: 512
  nhead: 4 
  num_encoder_layers: 3
  dim_feedforward: 512 
  dropout: 0.1

decoder_conf:
  num_decoder_layers: 3 
  dim_feedforward: 512
  dropout: 0.1

optim: AdamW
optim_conf:
  lr: 0.0005
  betas:
      - 0.9
      - 0.95
  weight_decay: 0.0000001

scheduler: StepLR
scheduler_conf:
  step_size: 5 
  gamma: 0.9


batch_size: 128
accum_grad: 2
epoch: 50
patience: 10
train_count: 5

